name: pywopwop-env

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.9
    - numpy=1.25
    - scipy=1.11
    - matplotlib=3.7
    - spyder=5.4
    - pyvista=0.42
    - vtk=9.2
    - h5py=3.7
    - pandas=2.0
    - openpyxl=3.0
    - pip=22
    - pip:
        - soundfile==0.11
